### PR TITLE
made namespace and prefixes configurable

### PR DESCRIPTION
**Pull request by czindel**
For some reasons I need to store my Module-Classes in a different namespace, so this must be configurable. In this context I also made the CSS class prefixes configurable to be more flexible.

### CODE REVIEW

**Comment by brunschgi** [comment]
Hi Christian

Thanks for your pull request. I thought about your use case using a namespace other than TC, but I have to say that this rare scenario is not worth doing this major change (this would imply changes on creating modules etc. as well). 

But I'm still curios ;-) What are these "some reasons"? Client dependent namespaces?

Cheers
Remo

**Comment by czindel** [comment]
I do not think this is really a rare scenario. There are various kinds of projects out there (mine is just one). Maybe this situation is rare in your daily business, but I am sure that this might be different in other companies and projects. There are reasons like:
- Integration in existing projects
- Just having different code conventions and structures
- Larger projects might need separation in "packages" like "App A" and "App B"
- Feels wrong to me to extend the framework with my project code
- HTML classes might be forced by backend system

In my experience such a framework should be somehow more flexible. It would be a shame if someone could not use the framework because of missing flexibility. Additionally I do not see why this is a major change. All I did should be backward compatible.

In my opinion there are more reasons for this change than against it. But if this makes no sense in the master project, than I will go on with my forked version.

**Comment by noelboss** [comment]
+1:  I agree on this with Christian, would be nice to have this flexibility.

**Comment by brunschgi** [comment]
I'm going to think about this again. Probably a modified version of Christians PR will find its way into 2.0.2.

**Comment by brunschgi** [comment]
Most of this flexibility – and some more – comes now bundled with TerrificJS 3.0.0.

**Pull request closed without merging**
